apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2       # Number of replicas (pods) for your application
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 100456454579.dkr.ecr.us-east-1.amazonaws.com/application:latest   # Reference to your Docker image
          ports:
            - containerPort: 8080      # Port your application listens on
          resources:
            requests:
              memory: "64Mi"         # Minimum memory required
              cpu: "250m"            # Minimum CPU required
            limits:
              memory: "128Mi"        # Maximum memory allowed
              cpu: "500m"            # Maximum CPU allowed