apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - port: 8080       # Port to expose your application on within the cluster
      protocol: TCP
      targetPort: 8080  # Port your application is listening on within the pod