apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 80  # Port through which the service is accessible within the cluster
      targetPort: 8080  # Port your ArgoCD server is listening on within the pod
  type: LoadBalancer  # Type of service (LoadBalancer for external access)